In [1]:
import numpy as np

In [2]:
#creating an array from the list
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [4]:
#creating an array with evenly spaced values
b = np.arange(0,10,3)    #start,stop and step values given
print("Array b:",b)

Array b: [0 3 6 9]


In [8]:
#creating an array filled with zeroes
d = np.zeros((2,3))   #2x3 matrix of zeroes
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#changing the parameter of previous one
d = np.zeros((2,3),dtype=int)   #2x3 matrix of zeroes(integer)
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [10]:
#creating an array filled with ones
e = np.ones((3,2))     #3x2 matrix of ones
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
#creating an identity matrix
f = np.eye(4)    #4x4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation Function

In [12]:
#reshape an array 
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))   #reshape to 1x3
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [14]:
#reshape an array 
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))   #reshape to 3x1
print("Reshaped array:\n",reshaped)

Reshaped array:
 [[1]
 [2]
 [3]]


In [15]:
#flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1)    #flatten to 1d array
print("flattened array f1:",flattened)

flattened array f1: [ 1  2  3  4  5  6  7  8  9 10]


In [17]:
#transpose an array
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n",transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [18]:
#stacking arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])   #to stack a2 and b2 vertically
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [19]:
#stacking arrays horizontaly
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])   #to stack a2 and b2 horizontaly
print("Stacked arrays:\n",stacked)

Stacked arrays:
 [1 2 3 4]


# Mathematical Functions

In [20]:
#addition 
g = np.array([1,2,3,4])
added = np.add(g,2)   #add 2 to each element 
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [21]:
#square(or any other power) to each element
squared = np.power(g,2)   #square of each element
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [22]:
#squareroot of each element
sqrt_val = np.sqrt(g)   
print("square root of g:",sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [24]:
print(a)
print(a1)
print(g)

[1 2 3]
[1 2 3]
[1 2 3 4]


In [25]:
dot_product = np.dot(a,a1)   #dot product of 2 arrays(same dimension)
print("Dot product of a and a1:",dot_product)

Dot product of a and a1: 14


# Statistical Functions

In [26]:
s = np.array([1,2,3,4])
mean = np.mean(s)    #to get mean value from the array
print("Mean of s:",mean)

Mean of s: 2.5


In [ ]:
#Variance of an array
var = np.var(s)
print("Variance of s:", var)

Variance of s: 1.25


In [28]:
#standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [29]:
#minimum element from an array
minimum = np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [30]:
#maximum element from an array
maximum = np.max(s)
print("Max of s:",maximum)

Max of s: 4


# Random sampling functions

In [34]:
#generating random values b/w 0 and 1
random_vals = np.random.rand(3)   
print("Random values:", random_vals)

Random values: [0.43924199 0.58589892 0.74593849]


In [38]:
#setting seed for reproducibility
np.random.seed(0)

#generating now
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [47]:
#generating random integers
rand_ints = np.random.randint(0,10,size=5)   #5 random integers between 0 and 10(n-1 rule)
print("Random integers:",rand_ints)

Random integers: [4 7 3 2 7]


In [50]:
#setting seed for reproducibility
np.random.seed(0)

#generating random integers
rand_ints = np.random.randint(0,10,size=5)   #5 random integers between 0 and 10(n-1 rule)
print("Random integers:",rand_ints)

Random integers: [5 0 3 3 7]


# Boolaen and Logical functions

In [51]:
t = np.array([True,True,True])
all_true = np.all(t)   #to check if all elements are true
print("All elements True:", all_true)

All elements True: True


In [52]:
mixed = np.array([True,False,True])
all_true = np.all(mixed)   #to check if all elements are true
print("All elements True:", all_true)

All elements True: False


In [53]:
mixed = np.array([True,False,True])
any_true = np.any(mixed)   #to check if any elements are true
print("Any elements True:", any_true)

Any elements True: True


In [54]:
f = np.array([False,False,False])
any_true = np.any(f)   #to check if any elements are true
print("Any elements True:", any_true)

Any elements True: False


# Set operations

In [55]:
#intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [57]:
#union of two arrays 
union = np.union1d(set_a,set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# Array attribute functions 

In [58]:
#array attributes
a = np.array([1,2,3])
shape = a.shape #shape of the array
size = a.size #no. of elements
dimensions = a.ndim   #no. of dimensions
dtype = a.dtype #data type of the array

print("Shape of a:",shape)
print("Size of a:",size)
print("Number of dimensions of a:",dimensions)
print("Data type of a:",dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# Other Functions

In [59]:
#create a copy of an array
a = a = np.array([1,2,3])
copied_array = np.copy(a)
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [60]:
#to get size of an array inn bytes
arraysize_in_bytes = a.nbytes
print("Size of a in bytes:",arraysize_in_bytes)

Size of a in bytes: 24


In [61]:
#checking if two arrays share memory
shared = np.shares_memory(a,copied_array)
print("Does both array share memory?",shared)

Does both array share memory? False
